// Shared
export const USER_NOT_WRITE_DATA = 'Enter correct data :)'

// Users
export const ADMIN_REQUEST = 'ADMIN_REQUEST'
export const ADMIN_REQUEST_END = 'ADMIN_REQUEST'
// SUCCESS
export const ADMIN_USERS_GET_SUCCESS = 'ADMIN_USERS_GET_SUCCESS'
export const ADMIN_USERS_EDIT_SUCCESS = 'ADMIN_USERS_EDIT_SUCCESS'
export const ADMIN_USERS_REMOVE_SUCCESS = 'ADMIN_USERS_REMOVE_SUCCESS'
// FAILURE
export const ADMIN_USERS_GET_FAILURE = 'ADMIN_USERS_GET_FAILURE'
export const ADMIN_USERS_EDIT_FAILURE = 'ADMIN_USERS_EDIT_FAILURE'
export const ADMIN_USERS_REMOVE_FAILURE = 'ADMIN_USERS_REMOVE_FAILURE'

// Orders =================

// SUCCESS
export const ADMIN_ORDERS_GET_SUCCESS = 'ADMIN_ORDERS_GET_SUCCESS'
export const ADMIN_ORDERS_EDIT_SUCCESS = 'ADMIN_USERS_EDIT_SUCCESS'
export const ADMIN_ORDERS_REMOVE_SUCCESS = 'ADMIN_USERS_REMOVE_SUCCESS'
// FAILURE
export const ADMIN_ORDERS_GET_FAILURE = 'ADMIN_ORDERS_GET_FAILURE'
export const ADMIN_ORDERS_EDIT_FAILURE = 'ADMIN_ORDERS_EDIT_FAILURE'
export const ADMIN_ORDERS_REMOVE_FAILURE = 'ADMIN_ORDERS_REMOVE_FAILURE'

// Products ================
// Shared
export const PRODUCT_GET_SEARCH_SUCCESS = 'PRODUCT_GET_SUCCESS_SEARCH'
export const PRODUCT_GET_SEARCH_FAILURE = 'PRODUCT_GET_FAILURE_SEARCH'

// SUCCESS
export const ADMIN_PRODUCTS_GET_SUCCESS = 'ADMIN_PRODUCTS_GET_SUCCESS'
export const ADMIN_PRODUCT_GET_BY_ID_SUCCESS = 'ADMIN_PRODUCT_GET_BY_ID_SUCCESS'
export const ADMIN_PRODUCTS_ADD_SUCCESS = 'ADMIN_PRODUCTS_ADD_SUCCESS'
export const ADMIN_PRODUCTS_EDIT_SUCCESS = 'ADMIN_PRODUCTS_EDIT_SUCCESS'
export const ADMIN_PRODUCTS_REMOVE_SUCCESS = 'ADMIN_PRODUCTS_REMOVE_SUCCESS'
// FAILURE
export const ADMIN_PRODUCTS_GET_FAILURE = 'ADMIN_PRODUCTS_GET_FAILURE'
export const ADMIN_PRODUCT_GET_BY_ID_FAILURE = 'ADMIN_PRODUCT_GET_BY_ID_FAILURE'
export const ADMIN_PRODUCTS_ADD_FAILURE = 'ADMIN_PRODUCTS_ADD_FAILURE'
export const ADMIN_PRODUCTS_EDIT_FAILURE = 'ADMIN_PRODUCTS_EDIT_FAILURE'
export const ADMIN_PRODUCTS_REMOVE_FAILURE = 'ADMIN_PRODUCTS_REMOVE_FAILURE'

// Categories =======================

// SUCCESS
export const ADMIN_CATEGORIES_GET_SUCCESS = 'ADMIN_CATEGORIES_GET_SUCCESS'
export const ADMIN_CATEGORY_GET_BY_ID_SUCCESS =
	'ADMIN_CATEGORY_GET_BY_ID_SUCCESS'
export const ADMIN_CATEGORIES_ADD_SUCCESS = 'ADMIN_CATEGORIES_ADD_SUCCESS'
export const ADMIN_CATEGORIES_EDIT_SUCCESS = 'ADMIN_CATEGORIES_EDIT_SUCCESS'
export const ADMIN_CATEGORIES_REMOVE_SUCCESS = 'ADMIN_CATEGORIES_REMOVE_SUCCESS'
// FAILURE
export const ADMIN_CATEGORIES_GET_FAILURE = 'ADMIN_CATEGORIES_GET_FAILURE'
export const ADMIN_CATEGORY_GET_BY_ID_FAILURE =
	'ADMIN_CATEGORY_GET_BY_ID_FAILURE'
export const ADMIN_CATEGORIES_ADD_FAILURE = 'ADMIN_CATEGORIES_ADD_FAILURE'
export const ADMIN_CATEGORIES_EDIT_FAILURE = 'ADMIN_CATEGORIES_EDIT_FAILURE'
export const ADMIN_CATEGORIES_REMOVE_FAILURE = 'ADMIN_CATEGORIES_REMOVE_FAILURE'

// Carts
// SUCCESS
export const ADMIN_CARTS_GET_SUCCESS = 'ADMIN_CARTS_GET_SUCCESS'
export const ADMIN_CARTS_REMOVE_SUCCESS = 'ADMIN_CARTS_REMOVE_SUCCESS'

// FAILURE
export const ADMIN_CARTS_GET_FAILURE = 'ADMIN_CATEGORIES_GET_FAILURE'
export const ADMIN_CARTS_REMOVE_FAILURE = 'ADMIN_CATEGORIES_REMOVE_FAILURE'
