// Login
export const AUTH_LOGIN_REQUEST = 'AUTH_LOGIN_REQUEST'
export const AUTH_LOGIN_SUCCESS = 'AUTH_LOGIN_SUCCESS'
export const AUTH_LOGIN_FAILURE = 'AUTH_LOGIN_FAILURE'
// Registration
export const AUTH_REG_REQUEST = 'AUTH_REG_REQUEST'
export const AUTH_REG_SUCCESS = 'AUTH_REG_SUCCESS'
export const AUTH_REG_FAILURE = 'AUTH_REG_FAILURE'
// Logout
export const AUTH_LOGOUT_REQUEST = 'AUTH_LOGOUT_REQUEST'
export const AUTH_LOGOUT = 'AUTH_LOGOUT'
export const AUTH_LOGOUT_FAILURE = 'AUTH_LOGOUT_FAILURE'
// Tokens
export const AUTH_REFRESH_TOKEN_REQUEST = 'AUTH_REFRESH_TOKEN_REQUEST'
export const AUTH_REFRESH_TOKEN_SUCCESS = 'REFRESH_TOKEN_SUCCESS'
export const AUTH_REFRESH_TOKEN_FAILURE = 'AUTH_REFRESH_TOKEN_FAILURE'
