export const CART_GET_SUCCESS = 'CART_GET_SUCCESS'
export const CART_ADD_SUCCESS = `CART_ADD_SUCCESS`
export const CART_REMOVE_SUCCESS = 'CART_REMOVE_SUCCESS'
// Failure
export const CART_GET_FAILURE = 'CART_GET_FAILURE'
export const CART_ADD_FAILURE = 'CART_ADD_FAILURE'
export const CART_REMOVE_FAILURE = 'CART_REMOVE_FAILURE'
