// Shared
export const CART_REQUEST = 'CART_REQUEST'

// Carts ==================
export const CART_GET_SUCCESS = 'CART_GET_SUCCESS'
export const CART_ADD_SUCCESS = `CART_ADD_SUCCESS`
export const CART_REMOVE_SUCCESS = 'CART_REMOVE_SUCCESS'
// Failure
export const CART_GET_FAILURE = 'CART_GET_FAILURE'
export const CART_ADD_FAILURE = 'CART_ADD_FAILURE'
export const CART_REMOVE_FAILURE = 'CART_REMOVE_FAILURE'

// Cart-items ==============
export const CART_ITEMS_GET_SUCCESS = 'CART_ITEMS_SUCCESS'
export const CART_ITEMS_ADD_SUCCESS = 'CART_ITEMS_ADD_SUCCESS'
export const CART_ITEMS_EDIT_SUCCESS = 'CART_ITEMS_EDIT_SUCCESS '
export const CART_ITEMS_REMOVE_SUCCESS = 'CART_ITEMS_REMOVE_SUCCESS'
// Failure
export const CART_ITEMS_GET_FAILURE = 'CART_ITEMS_GET_FAILURE'
export const CART_ITEMS_ADD_FAILURE = 'CART_ITEMS_ADD_FAILURE'
export const CART_ITEMS_EDIT_FAILURE = 'CART_ITEMS_EDIT_FAILURE'
export const CART_ITEMS_REMOVE_FAILURE = 'CART_ITEMS_REMOVE_FAILURE'
