// ORDER
export const ORDER_REQUEST = 'ORDER_REQUEST'

// Order Success
export const ORDER_GET_ADMIN_SUCCESS = 'ORDER_GET_ADMIN_SUCCESS'
export const ORDER_GET_SUCCESS = 'ORDER_GET_SUCCESS'
export const ORDER_GET_BY_ID_SUCCESS = 'ORDER_GET_BY_ID_SUCCESS'
export const ORDER_ADD_SUCCESS = 'ORDER_ADD_SUCCESS'
export const ORDER_EDIT_SUCCESS = 'ORDER_EDIT_SUCCESS'
export const ORDER_REMOVE_SUCCESS = 'ORDER_REMOVE_SUCCESS'
// Order Failure
export const ORDER_GET_ADMIN_FAILURE = 'ORDER_GET_ADMIN_FAILURE'
export const ORDER_GET_FAILURE = 'ORDER_GET_FAILURE'
export const ORDER_GET_BY_ID_FAILURE = 'ORDER_GET_BY_ID_FAILURE'
export const ORDER_ADD_FAILURE = 'ORDER_ADD_FAILURE'
export const ORDER_EDIT_FAILURE = 'ORDER_EDIT_FAILURE'
export const ORDER_REMOVE_FAILURE = 'ORDER_REMOVE_FAILURE'

// ORDER-ITEMS Request
export const ORDER_ITEMS_REQUEST = 'ORDER_ITEMS_REQUEST'

// ORDER-ITEMS Success
export const ORDER_ITEMS_GET_ADMIN_SUCCESS = 'ORDER_ITEMS_GET_ADMIN_SUCCESS'
export const ORDER_ITEMS_GET_SUCCESS = 'ORDER_ITEMS_GET_SUCCESS'
export const ORDER_ITEMS_BY_ID_SUCCESS = 'ORDER_ITEMS_BY_ID_SUCCESS'
export const ORDER_ITEMS_ADD_SUCCESS = 'ORDER_ITEMS_ADD_SUCCESS'
export const ORDER_ITEMS_EDIT_SUCCESS = 'ORDER_ITEMS_EDIT_SUCCESS'
export const ORDER_ITEMS_REMOVE_SUCCESS = 'ORDER_ITEMS_REMOVE_SUCCESS'
// ORDER-ITEMS Failure
export const ORDER_ITEMS_GET_ADMIN_FAILURE = 'ORDER_ITEMS_GET_ADMIN_FAILURE'
export const ORDER_ITEMS_GET_FAILURE = 'ORDER_ITEMS_GET_FAILURE'
export const ORDER_ITEMS_BY_ID_FAILURE = 'ORDER_ITEMS_BY_ID_FAILURE'
export const ORDER_ITEMS_ADD_FAILURE = 'ORDER_ITEMS_ADD_FAILURE'
export const ORDER_ITEMS_EDIT_FAILURE = 'ORDER_ITEMS_EDIT_FAILURE'
export const ORDER_ITEMS_REMOVE_FAILURE = 'ORDER_ITEMS_REMOVE_FAILURE'
